### ISSUE TITLE
ZeroIoC.ServiceIsNotRegistered: 'Type ZeroIocTest.IUserService is missing in resolver

### ISSUE THREAD

**Issue by ekalchev** [byme8/ZeroIoC#2]
I am getting this exception with the following registration code

```Csharp
public partial class Container : ZeroIoCContainer
    {
        protected override void Bootstrap(IZeroIoCContainerBootstrapper bootstrapper)
        {
            bootstrapper.AddSingleton<Helper>();
            bootstrapper.AddSingleton<IUserService, UserService>();
            bootstrapper.AddScoped<IUserService, UserService>();
        }
    }
```
Generated code
```CSharp
public Container()
        {
          Resolvers.Add(typeof(global::ZeroIocTest.Helper), new SingletonResolver<ZeroIocTest_HelperCreator, global::ZeroIocTest.Helper>());

        }

**Comment by byme8** [comment]
The registration of multiple implementations is not supported at the moment. There were had plans for it, but I decided to keep it simple and postponed the feature.

I guess will add a compilation error with an explanation for such a case to avoid misunderstanding. Maybe in the future, I will work on it.

**Comment by byme8** [comment]
Pushed version 0.3.0. It has an error message that explains that there is no support for multiple implementations,
