### ISSUE TITLE
protected member declared in sealed type

### ISSUE THREAD

**Issue by appel1** [byme8/ZeroIoC#6]
Is there a plan here to allow inheriting from a container or should the scope ctor be private? 

`6>Container_ZeroIoCContainer.cs(78,19): Warning CS0628 : 'Container.Container(Dictionary<Type, IInstanceResolver>, Dictionary<Type, IInstanceResolver>, bool)': new protected member declared in sealed type`

It would be useful to allow inheritance and let inheritors add more registrations.

**Comment by byme8** [comment]
To add more registrations you can merge multiple containers into one.
Here example:
``` csharp
public class DomainZeroIoCContainer : ZeroIoCContainer
{
}

public class DataZeroIoCContainer : ZeroIoCContainer
{
}

// ...

public class AppZeroIoCContainer : ZeroIoCContainer
{
}


var appContainer = new AppZeroIoCContainer();
app.Merge(new DomainZeroIoCContainer());
app.Merge(new DataZeroIoCContainer());
```

**Comment by appel1** [comment]
Had missed the Merge method, thanks. 

Then it would be nice if the generated code did not trigger the CS0628 warning.
